# Generated by Django 5.0.3 on 2024-03-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_Name', models.CharField(default='', max_length=100)),
                ('Product_Name', models.CharField(default='', max_length=150)),
                ('Product_Review', models.TextField(default='')),
                ('Product_Image', models.ImageField(upload_to='productphotos')),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
